### PR TITLE
CR-1266: Add test for transparent optimization bug

### PR DESCRIPTION
**Pull request by jagraff**
Because the tester uses python2.7, I have to implement a timeout using poll() instead of passing timeout as an argument

### CODE REVIEW

**Comment by bejayoharen** [comment]
@whydna this looks good to me, but thought you could double check it.

**Review by cyburgee — APPROVED** [review]

**Comment by whydna** [comment]
@jagraff LGTM - another option is we can just use Python 3+ for this.

**Comment by jagraff** [comment]
> @jagraff LGTM - another option is we can just use Python 3+ for this.

Yea if we can do that that's probably better, although I'm not sure what the organizational standard is

**Comment by whydna** [comment]
@jagraff I think it should be OK since all of this stuff lives inside a virtual env - we'd just need add in the README to create the environment with path to python 3. In either case, I don't think it's a big deal either way.

One question - does this mean that every task will need to run for at least 10 seconds?

**Comment by jagraff** [comment]
> One question - does this mean that every task will need to run for at least 10 seconds?

No - if a task completes, then poll() won't return None, so the task will finish early. The only way that a task would run for the full 10 seconds is if it times out, otherwise as soon as it finished poll() would return not None, and the loop would complete.

**Comment by whydna** [comment]
https://media.giphy.com/media/l2Sq5GffrCyUMEXjW/giphy.gif

**Pull request merged**
